// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/slackgist.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_slackgist_9c8b6ee7df18b7af, []int{0}
}
func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (dst *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(dst, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EchoResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_slackgist_9c8b6ee7df18b7af, []int{1}
}
func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (dst *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(dst, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StatusRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_slackgist_9c8b6ee7df18b7af, []int{2}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StatusRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type StatusResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_slackgist_9c8b6ee7df18b7af, []int{3}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type BuildRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Options              string   `protobuf:"bytes,3,opt,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_slackgist_9c8b6ee7df18b7af, []int{4}
}
func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (dst *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(dst, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BuildRequest) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

type BuildResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_slackgist_9c8b6ee7df18b7af, []int{5}
}
func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (dst *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(dst, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BuildResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "api.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "api.EchoResponse")
	proto.RegisterType((*StatusRequest)(nil), "api.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "api.StatusResponse")
	proto.RegisterType((*BuildRequest)(nil), "api.BuildRequest")
	proto.RegisterType((*BuildResponse)(nil), "api.BuildResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Slackgist service

type SlackgistClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
}

type slackgistClient struct {
	cc *grpc.ClientConn
}

func NewSlackgistClient(cc *grpc.ClientConn) SlackgistClient {
	return &slackgistClient{cc}
}

func (c *slackgistClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/api.Slackgist/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slackgistClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/api.Slackgist/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slackgistClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	out := new(BuildResponse)
	err := grpc.Invoke(ctx, "/api.Slackgist/Build", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Slackgist service

type SlackgistServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
}

func RegisterSlackgistServer(s *grpc.Server, srv SlackgistServer) {
	s.RegisterService(&_Slackgist_serviceDesc, srv)
}

func _Slackgist_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlackgistServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Slackgist/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlackgistServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Slackgist_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlackgistServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Slackgist/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlackgistServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Slackgist_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlackgistServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Slackgist/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlackgistServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Slackgist_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Slackgist",
	HandlerType: (*SlackgistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Slackgist_Echo_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Slackgist_Status_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _Slackgist_Build_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/slackgist.proto",
}

func init() { proto.RegisterFile("api/slackgist.proto", fileDescriptor_slackgist_9c8b6ee7df18b7af) }

var fileDescriptor_slackgist_9c8b6ee7df18b7af = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4d, 0x6a, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x7e, 0x6c, 0x32, 0x71, 0x4a, 0x32, 0x81, 0x62, 0x4c, 0x17, 0x45, 0x9b, 0x86,
	0x2c, 0x6c, 0x68, 0x77, 0x81, 0x2c, 0x62, 0xc8, 0x05, 0x92, 0x13, 0x28, 0x8e, 0x70, 0x44, 0x5c,
	0x4b, 0xad, 0xe4, 0x0b, 0xf4, 0x0a, 0x3d, 0x5a, 0x7b, 0x84, 0x1e, 0xa4, 0x58, 0x92, 0xc1, 0xd9,
	0xd4, 0xd0, 0x9d, 0xe6, 0xe9, 0xe9, 0x9b, 0xd1, 0x93, 0x60, 0x49, 0x25, 0x4f, 0x55, 0x49, 0xf3,
	0x6b, 0xc1, 0x95, 0x4e, 0xe4, 0xbb, 0xd0, 0x02, 0x87, 0x54, 0xf2, 0xf8, 0xa1, 0x10, 0xa2, 0x28,
	0x59, 0xda, 0x18, 0x68, 0x55, 0x09, 0x4d, 0x35, 0x17, 0x95, 0xb2, 0x16, 0xf2, 0x04, 0xd3, 0x7d,
	0x7e, 0x11, 0x07, 0xf6, 0x56, 0x33, 0xa5, 0x31, 0x82, 0xe0, 0x95, 0x29, 0x45, 0x0b, 0x16, 0x79,
	0x8f, 0xde, 0x6a, 0x72, 0x68, 0x4b, 0xb2, 0x82, 0xd0, 0x1a, 0x95, 0x14, 0x95, 0x62, 0x7f, 0x38,
	0xb7, 0x30, 0x3b, 0x6a, 0xaa, 0x6b, 0xd5, 0x0b, 0x45, 0x84, 0xd1, 0x95, 0x57, 0xe7, 0x68, 0x60,
	0x64, 0xb3, 0x26, 0x19, 0xdc, 0xb5, 0xc7, 0xfb, 0x5a, 0xe1, 0x3d, 0xf8, 0xca, 0x78, 0x1d, 0xc1,
	0x55, 0x24, 0x83, 0x30, 0xab, 0x79, 0x79, 0xee, 0x9f, 0x20, 0x82, 0x40, 0x48, 0x13, 0x48, 0x34,
	0xb4, 0x3b, 0xae, 0x24, 0x3b, 0x98, 0x39, 0xc6, 0x7f, 0xc7, 0x78, 0xfe, 0xf6, 0x60, 0x72, 0x6c,
	0xdf, 0x04, 0xb7, 0x30, 0x6a, 0x12, 0xc4, 0x79, 0x42, 0x25, 0x4f, 0x3a, 0xa9, 0xc7, 0x8b, 0x8e,
	0x62, 0x9b, 0x91, 0xf9, 0xc7, 0xd7, 0xcf, 0xe7, 0x00, 0xc8, 0x38, 0x65, 0xf9, 0x45, 0x6c, 0xbc,
	0x35, 0xee, 0xc1, 0xb7, 0xb9, 0x20, 0x1a, 0xfb, 0x4d, 0xc6, 0xf1, 0xf2, 0x46, 0x73, 0x10, 0x34,
	0x90, 0x90, 0x04, 0xa9, 0x1d, 0xa8, 0xc1, 0xec, 0x60, 0x6c, 0xae, 0x85, 0xb6, 0x69, 0x37, 0xa6,
	0x18, 0xbb, 0x92, 0x63, 0x2c, 0x0c, 0x63, 0x4a, 0xfc, 0xf4, 0xd4, 0xe8, 0x1b, 0x6f, 0x7d, 0xf2,
	0xcd, 0xd7, 0x79, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x30, 0x2e, 0xfb, 0xce, 0x74, 0x02, 0x00,
	0x00,
}
