language: python

python:
  - '2.6'
  - '2.7'
  - 'pypy'

install: "python setup.py install"

script: "dna -h"

deploy:
  provider: pypi
  user: allanino
  password:
    secure: f6A4pg0MWM11U4i+MViOMNe/YM9LT6v/jAFs6JRQ7jp+2eVjuzFlfByVn0sLdALExHi4sno66j7aLTGJcSlwlRZUt/Wss1C+4Rt1D+KrzriFdH8WANKzTF63fh8cZDYMdEerzCkcPwzcBB5tmdpMXq44LIaw/d4a7hF2L5bNqlc=
  on:
    all_branches: true
    tags: true
    repo: allanino/DNA
