#
# $Revision: 1.1.1.1 $
#

MAKEDEFINES = ../include/makedef
MAKERULES = ../include/makerule

include $(MAKEDEFINES)

LIBOBJS = shell.o test.o
LIB = libapp.a

default: lib

include $(MAKERULES)
