#
# $Revision: 1.1.1.1 $
#

MAKEDEFINES = ../include/makedef
MAKERULES = ../include/makerule

include $(MAKEDEFINES)

LIBOBJS = kern.o sem.o init.o
LIB = libkern.a

default: lib

include $(MAKERULES)
