// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/kuberp.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_kuberp_f88d1b2d9b7250d9, []int{0}
}
func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (dst *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(dst, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EchoResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_kuberp_f88d1b2d9b7250d9, []int{1}
}
func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (dst *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(dst, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ProxyRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	Origin               string   `protobuf:"bytes,5,opt,name=origin" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyRequest) Reset()         { *m = ProxyRequest{} }
func (m *ProxyRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyRequest) ProtoMessage()    {}
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_kuberp_f88d1b2d9b7250d9, []int{2}
}
func (m *ProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyRequest.Unmarshal(m, b)
}
func (m *ProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyRequest.Marshal(b, m, deterministic)
}
func (dst *ProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyRequest.Merge(dst, src)
}
func (m *ProxyRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyRequest.Size(m)
}
func (m *ProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyRequest proto.InternalMessageInfo

func (m *ProxyRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ProxyRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ProxyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProxyRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ProxyRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type ProxyResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyResponse) Reset()         { *m = ProxyResponse{} }
func (m *ProxyResponse) String() string { return proto.CompactTextString(m) }
func (*ProxyResponse) ProtoMessage()    {}
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_kuberp_f88d1b2d9b7250d9, []int{3}
}
func (m *ProxyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyResponse.Unmarshal(m, b)
}
func (m *ProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyResponse.Marshal(b, m, deterministic)
}
func (dst *ProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyResponse.Merge(dst, src)
}
func (m *ProxyResponse) XXX_Size() int {
	return xxx_messageInfo_ProxyResponse.Size(m)
}
func (m *ProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyResponse proto.InternalMessageInfo

func (m *ProxyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ProxyResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "api.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "api.EchoResponse")
	proto.RegisterType((*ProxyRequest)(nil), "api.ProxyRequest")
	proto.RegisterType((*ProxyResponse)(nil), "api.ProxyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Kuberp service

type KuberpClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	Proxy(ctx context.Context, in *ProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error)
}

type kuberpClient struct {
	cc *grpc.ClientConn
}

func NewKuberpClient(cc *grpc.ClientConn) KuberpClient {
	return &kuberpClient{cc}
}

func (c *kuberpClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/api.Kuberp/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuberpClient) Proxy(ctx context.Context, in *ProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error) {
	out := new(ProxyResponse)
	err := grpc.Invoke(ctx, "/api.Kuberp/Proxy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Kuberp service

type KuberpServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	Proxy(context.Context, *ProxyRequest) (*ProxyResponse, error)
}

func RegisterKuberpServer(s *grpc.Server, srv KuberpServer) {
	s.RegisterService(&_Kuberp_serviceDesc, srv)
}

func _Kuberp_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuberpServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Kuberp/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuberpServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuberp_Proxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuberpServer).Proxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Kuberp/Proxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuberpServer).Proxy(ctx, req.(*ProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kuberp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Kuberp",
	HandlerType: (*KuberpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Kuberp_Echo_Handler,
		},
		{
			MethodName: "Proxy",
			Handler:    _Kuberp_Proxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/kuberp.proto",
}

func init() { proto.RegisterFile("api/kuberp.proto", fileDescriptor_kuberp_f88d1b2d9b7250d9) }

var fileDescriptor_kuberp_f88d1b2d9b7250d9 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x9b, 0x44, 0x3a, 0x56, 0x89, 0x8b, 0xc8, 0x12, 0x3c, 0xc8, 0x5e, 0x2c, 0x3d,
	0x24, 0xa8, 0xb7, 0x82, 0x07, 0x41, 0x4f, 0x5e, 0xa4, 0x6f, 0xb0, 0xad, 0x4b, 0xb2, 0xd4, 0xee,
	0xac, 0xd9, 0x8d, 0x28, 0x78, 0xf2, 0xee, 0xc9, 0x47, 0xf3, 0x15, 0x7c, 0x10, 0xd9, 0x3f, 0x42,
	0x4e, 0xf6, 0x36, 0xf3, 0x9b, 0x8f, 0x6f, 0x66, 0xbf, 0x85, 0x82, 0x6b, 0x59, 0x6f, 0xfa, 0x95,
	0xe8, 0x74, 0xa5, 0x3b, 0xb4, 0x48, 0xc6, 0x5c, 0xcb, 0xf2, 0xb4, 0x41, 0x6c, 0x9e, 0x44, 0xed,
	0xa6, 0x5c, 0x29, 0xb4, 0xdc, 0x4a, 0x54, 0x26, 0x48, 0xd8, 0x39, 0xec, 0xdf, 0xad, 0x5b, 0x5c,
	0x8a, 0xe7, 0x5e, 0x18, 0x4b, 0x28, 0xec, 0x6d, 0x85, 0x31, 0xbc, 0x11, 0x34, 0x39, 0x4b, 0x66,
	0x93, 0xe5, 0x5f, 0xcb, 0x66, 0x30, 0x0d, 0x42, 0xa3, 0x51, 0x19, 0xf1, 0x8f, 0xf2, 0x1d, 0xa6,
	0x0f, 0x1d, 0xbe, 0xbe, 0xed, 0xf4, 0x24, 0x04, 0xd2, 0x8d, 0x54, 0x8f, 0x74, 0xe4, 0xb1, 0xaf,
	0x1d, 0x53, 0x7c, 0x2b, 0xe8, 0x38, 0x30, 0x57, 0x3b, 0xa6, 0xb9, 0x6d, 0x69, 0x1a, 0x98, 0xab,
	0xc9, 0x09, 0xe4, 0xd8, 0xc9, 0x46, 0x2a, 0x9a, 0x79, 0x1a, 0x3b, 0x76, 0x03, 0x07, 0x71, 0xfb,
	0xae, 0x43, 0x9d, 0x85, 0xb1, 0xdc, 0xf6, 0x26, 0x1e, 0x10, 0xbb, 0xcb, 0xcf, 0x04, 0xf2, 0x7b,
	0x9f, 0x23, 0xb9, 0x86, 0xd4, 0xbd, 0x9a, 0x14, 0x15, 0xd7, 0xb2, 0x1a, 0x24, 0x55, 0x1e, 0x0d,
	0x48, 0xd8, 0xc4, 0x8a, 0x8f, 0xef, 0x9f, 0xaf, 0x11, 0xb0, 0xac, 0x16, 0xeb, 0x16, 0x17, 0xc9,
	0x9c, 0xdc, 0x42, 0xe6, 0x8f, 0x21, 0x41, 0x3d, 0x8c, 0xa5, 0x24, 0x43, 0x14, 0x1d, 0x8e, 0xbd,
	0xc3, 0x21, 0x9b, 0xd4, 0x2f, 0x17, 0xb5, 0x76, 0xa3, 0x45, 0x32, 0x5f, 0xe5, 0xfe, 0xab, 0xae,
	0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xce, 0x79, 0x5d, 0xdb, 0xe1, 0x01, 0x00, 0x00,
}
