apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: test-deployment-1
    namespace: api
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - name: http
          containerPort: 80
