#
# $Revision: 1.1.1.1 $
#

MAKEDEFINES = ../include/makedef
MAKERULES = ../include/makerule

include $(MAKEDEFINES)

LIBOBJS = kstdio.o stdio.o string.o
LIB = libc.a

default: lib

include $(MAKERULES)

